### ISSUE TITLE
Undefined variable watcher

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratch-corpus#1]
@PullJosh I think this project contains a variable watcher for a variable that isn't actually defined?

https://scratch.mit.edu/projects/97891022/

Pretty sure that's not allowed. Although @nathan's [sb2 validator](http://nathan.github.io/sb2/validate/) allows it...

**Comment by PullJosh** [comment]
I can't seem to find it. :/

However, a separate project which includes watchers for non-existent variables/lists would be a good one. I'll throw that together...
_Update:_ Here it is: https://scratch.mit.edu/projects/135980420/

**Comment by tjvr** [comment]
Sorry, I meant to paste the offending variable name!

`ثم نفس سقطت وبالتحديد،`, apparently

**Comment by tjvr** [comment]
> However, a separate project which includes watchers for non-existent variables/lists would be a good one.

Is it possible to create that using the Scratch 2 editor?

**Comment by PullJosh** [comment]
Almost certainly not. :P

**Comment by tjvr** [comment]
> Almost certainly not. :P

Probably better not include that project then! :P

Please could you fix the existing one? :)

**Comment by PullJosh** [comment]
> Please could you fix the existing one? :)  

I can't seem to find the issue. `ثم نفس سقطت وبالتحديد،` doesn't appear anywhere in the project for me:
![image](https://cloud.githubusercontent.com/assets/5458180/21116919/8dfa9e1e-c085-11e6-82eb-6b12d671945c.png)

**Comment by tjvr** [comment]
Oh interesting...

Upon further investigation, I think you're right! It looks like it's actually a kurt bug :-) https://github.com/tjvr/kurt/issues/36

**Comment by PullJosh** [comment]
I suppose that means the corpus is working as intended. ;)

**Comment by tjvr** [comment]
Precisely! :D
